services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel2-app
        volumes:
            - .:/var/www
        ports:
            - "${APP_PORT:-9001}:9000"
        networks:
            - laravel-shared-net

    web:
        image: nginx:alpine
        container_name: laravel2-nginx
        ports:
            - "${NGINX_PORT:-8001}:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-shared-net
        depends_on:
            - app

networks:
    laravel-shared-net:
        external: true
